"""
Guards the split-conformal RUL interval: `predict_rul` must return a calibrated
band that brackets its own point estimate and stays within [0, rul_cap]. We also
sanity-check empirical coverage on near-failure rows (kept loose to avoid flake).

Requires a trained model.pkl (regenerated by train.py with `conformal_q`) and the
CMAPSS training data; skipped otherwise.
"""

import os

import pandas as pd
import pytest

from model.features import DROP_SENSORS, RAW_COLS, add_rolling_features
from model import predict as predict_mod

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH = os.path.join(BASE, "data", "train_FD001.txt")
MODEL_PATH = os.path.join(BASE, "model", "model.pkl")


@pytest.fixture(scope="module")
def rows_with_truth():
    if not os.path.exists(DATA_PATH) or not os.path.exists(MODEL_PATH):
        pytest.skip("requires train_FD001.txt and a trained model.pkl")

    predict_mod.load_bundle.cache_clear()
    bundle = predict_mod.load_bundle()
    if bundle.get("conformal_q") is None:
        pytest.skip("model.pkl predates conformal calibration — re-run train.py")
    feature_cols = bundle["feature_cols"]

    df = pd.read_csv(DATA_PATH, sep=r"\s+", header=None, names=RAW_COLS)
    df.drop(columns=DROP_SENSORS, inplace=True)
    max_cycle = df.groupby("unit")["cycle"].max().rename("mc")
    df = df.join(max_cycle, on="unit")
    df["RUL"] = (df["mc"] - df["cycle"]).clip(upper=bundle["rul_cap"])
    sensor_cols = [c for c in df.columns if c.startswith("s")]
    df = add_rolling_features(df, sensor_cols)

    sample = df.sample(n=300, random_state=0)
    rows = sample[feature_cols].to_dict("records")
    truths = sample["RUL"].tolist()
    return rows, truths, bundle["rul_cap"]


def test_interval_brackets_point_and_stays_in_range(rows_with_truth):
    rows, _, cap = rows_with_truth
    for r in rows[:50]:
        p = predict_mod.predict_rul(r)
        assert {"rul_low", "rul_high", "rul_interval"} <= p.keys()
        assert 0.0 <= p["rul_low"] <= p["rul"] <= p["rul_high"] <= float(cap)
        assert p["rul_interval"] == 0.90


def test_empirical_coverage_is_reasonable(rows_with_truth):
    rows, truths, _ = rows_with_truth
    preds = [predict_mod.predict_rul(r) for r in rows]
    covered = sum(
        1 for p, t in zip(preds, truths) if p["rul_low"] <= t <= p["rul_high"]
    )
    coverage = covered / len(rows)
    # Target is 90%; intervals are clamped at the RUL cap which can clip coverage at
    # the plateau, so keep a generous lower bound — this is a calibration smoke test.
    assert coverage >= 0.75
